### ISSUE TITLE
[Bug] Unhandled param in url: provider_token

### ISSUE THREAD

**Issue by rileyhawk1417** [AppFlowy-IO/AppFlowy-Cloud#246] opened 2024-01-04 18:30 UTC
**Describe the bug**
In the code `provider_token` is not handled, which throws an error when logging in via OAuth.

**To Reproduce**
1. Download AppFlowy 0.4.1
2. Launch and change server to AppFlowyCloud
3. Click user and log in using any of the OAuth buttons.
4. After confirming login from the browser check AppFlowy terminal log.

**Expected behavior**
Log into AppFlowy and sync data.

**Screenshots**

The screenshot below is the error that appears on AppFlowy after trying to sign in using OAuth.
![AppFlowy Application error](https://i.imgur.com/pRoItsc.png)

This screenshot are the logs when AppFlowy is run from the terminal.
![Terminal Logs](https://i.imgur.com/oi2hSL3.png)

**Desktop (please complete the following information):**
 - OS: Linux (ArchCraft)
 - Version 0.4.1

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]

**Comment by speed2exe** [comment] 2024-01-05 02:47
@rileyhawk1417 

Hi thanks for filing the issue. I dont think it's because of `provider_token`.
So in the cloud, there are 2 services that appflowy connects to:
- Authentication server (which seems to be working fine)
- AppFlowy Cloud server (which returns 404)

I cant reproduce the error though. Just checking, you've set the server url to `https://beta.appflowy.cloud`?

**Comment by speed2exe** [comment] 2024-01-05 06:02
@rileyhawk1417 I think I might have found the bug, you probably put extra `/` at the end of the url in cloud settings.
```
correct:   https://beta.appflowy.cloud
incorrect: https://beta.appflowy.cloud/
```
This bug will be fixed in the future iteration

**Comment by rileyhawk1417** [comment] 2024-01-05 08:19
Thanks it worked. Should the issue remain open or just closed?

**Comment by speed2exe** [comment] 2024-01-05 08:28
@rileyhawk1417 we can keep this open until the issue is fixed.

**Closed** 2024-02-19 13:34 UTC
